Exception info: 
java.lang.NullPointerException
	at MySQLDatabase.prepare(MySQLDatabase.java:84)
	at MySQLDatabase.getData(MySQLDatabase.java:120)
	at Users.getUser(Users.java:378)
	at MainTest.main(MainTest.java:42)
[SQL Query:, select affiliationName from _affiliations where affiliationId = ?;]
[Values to be bound:, 1]
Current time: 2020-04-24 14:14:15.949

Exception info: 
DLException
	at MySQLDatabase.prepare(MySQLDatabase.java:104)
	at MySQLDatabase.getData(MySQLDatabase.java:120)
	at Users.getUser(Users.java:378)
	at MainTest.main(MainTest.java:42)
[SQL Query:, select affiliationName from _affiliations where affiliationId = ?;]
[Values to be bound:, Values to be bound:, 1]
Current time: 2020-04-24 14:14:15.951

